[tools]
node = "latest"
python = "latest"
bun = "latest"
gh = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@withgraphite/graphite-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "java"]
minimum_release_age = "7d"
experimental = true
