keybindings:
  prs:
    - key: T
      command: >-
        tmux new-window '
          gh enhance -R {{.RepoName}} {{.PrNumber}}
        '
theme:
  colors:
    text:
      primary: "#c0caf5"
            secondary: "#bb9af7"
            inverted: "#24283b"
            faint: "#565f89"
            warning: "#e0af68"
            success: "#9ece6a"
            error: "#f7768e"
        background:
            selected: "#414868"
        border:
            primary: "#565f89"
            secondary: "#414868"
            faint: "#414868"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
pager:
  diff: hunk pager
  confirmQuit: true
  showAuthorIcons: true
