"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[▸▹ ](dimmed white)"

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$docker_context\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
($container)"""

right_format = """
$env_var.ZMX_SESSION\
$kubernetes\
$c\
$cpp\
$cmake\
$deno\
$dotnet\
$golang\
$java\
$lua\
$maven\
$nodejs\
$bun\
$python\
$terraform\
$status\
$character\
$cmd_duration\n"""

[character]
format = "$symbol "
success_symbol = "[◎](bold italic bright-yellow)"
error_symbol = "[○](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"

[fill]
symbol = ' '

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
fish_style_pwd_dir_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[golang]
format = ' $symbol($version) '

[java]
format = ' $symbol($version) '

[maven]
format = ' $symbol($version) '

[nodejs]
format = ' $symbol($version) '

[python]
python_binary = [['mise', 'exec', '--', 'python']]
format = ' $symbol($version) '

[env_var.ZMX_SESSION]
symbol = " "
format = "[$symbol$env_value]($style) "
style = "bold magenta"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
