#!/bin/bash

# # Colors taken from tokyonight theme
# red="0xfff7768e"
# blue="0xff7aa2f7"
#
# options=(
# 	style=round
# 	width=6.0
# 	hidpi=off
# 	active_color="$red"
# 	inactive_color="$blue"
# )

options=(
  style=round
  width=6.0
  hidpi=off
  active_color=0xc0e2e2e3
  inactive_color=0xc02c2e34
  background_color=0x302c2e34
)

borders "${options[@]}"
