#!/bin/bash

# Colors taken from tokyonight theme
red="0xfff7768e"
blue="0xff7aa2f7"

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="$red"
	inactive_color="$blue"
)

borders "${options[@]}"

